(part "74HCT2G125DC_125"
    (packageRef "SOP50P310X100-8N")
    (interface
        (port "1" (symbPinId 1) (portName "%1OE%") (portType INOUT))
        (port "2" (symbPinId 2) (portName "1A") (portType INOUT))
        (port "3" (symbPinId 3) (portName "2Y") (portType INOUT))
        (port "4" (symbPinId 4) (portName "GND") (portType INOUT))
        (port "5" (symbPinId 5) (portName "2A") (portType INOUT))
        (port "6" (symbPinId 6) (portName "1Y") (portType INOUT))
        (port "7" (symbPinId 7) (portName "%2OE%") (portType INOUT))
        (port "8" (symbPinId 8) (portName "VCC") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Mouser_Part_Number" "771-HCT2G125DC125")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Nexperia/74HCT2G125DC125?qs=P62ublwmbi%252B%252B1eQ2FD8Fxg%3D%3D")
    (property "Manufacturer_Name" "Nexperia")
    (property "Manufacturer_Part_Number" "74HCT2G125DC,125")
    (property "Description" "74HC(T)2G125 - Dual buffer/line driver; 3-state@en-us")
    (property "Datasheet_Link" "https://assets.nexperia.com/documents/data-sheet/74HC_HCT2G125.pdf")
    (property "symbolName1" "74HCT2G125DC_125")
)
